import{Game}from"./engine/Game.js";import{UI}from"./ui/UI.js";import{DesignStore}from"./customization/DesignStore.js";import{Designer}from"./customization/Designer.js";
const ui=new UI,store=new DesignStore,game=new Game(document.getElementById("gameCanvas"),ui,store),designer=new Designer(ui,store,()=>{game.starfield.sync()});
const settings=()=>({level:Number(ui.startLevel.value||1),sound:ui.soundToggle.checked});
ui.startButton.addEventListener("click",()=>{const s=settings();localStorage.setItem("helveticshotStartLevel",s.level);localStorage.setItem("helveticshotSound",s.sound?"1":"0");game.start(s.level,s.sound)});ui.manualButton.addEventListener("click",()=>ui.showManual());ui.manualBackButton.addEventListener("click",()=>ui.showMenu());ui.designerButton.addEventListener("click",()=>ui.showDesigner());ui.designerBackButton.addEventListener("click",()=>ui.showMenu());ui.restartButton.addEventListener("click",()=>game.restart());ui.gameOverMenuButton.addEventListener("click",()=>game.toMenu());ui.pauseButton.addEventListener("click",()=>game.togglePause());ui.resumeButton.addEventListener("click",()=>game.togglePause());ui.pauseMenuButton.addEventListener("click",()=>game.toMenu());addEventListener("keydown",e=>{if((e.code==="KeyP"||e.code==="Escape")&&(game.state==="playing"||game.state==="paused")){e.preventDefault();game.togglePause()}});const sl=localStorage.getItem("helveticshotStartLevel");if(sl&&[...ui.startLevel.options].some(o=>o.value===sl))ui.startLevel.value=sl;const ss=localStorage.getItem("helveticshotSound");if(ss!==null)ui.soundToggle.checked=ss==="1";

const refreshLocalHi=()=>{if(ui.menuHighScore)ui.menuHighScore.textContent=String(game.highScore||0).padStart(6,"0");};
refreshLocalHi();
ui.resetHighScoreButton?.addEventListener("click",()=>{if(confirm("Lokalen Highscore auf diesem Gerät/Browser wirklich zurücksetzen? / Reset local high score on this device/browser?")){game.highScore=0;localStorage.removeItem("helveticshotHighScore");localStorage.removeItem("retroInvadersHighScore");refreshLocalHi();game.syncHud();}});
addEventListener("storage",refreshLocalHi);
