import{Game}from"./engine/Game.js";import{UI}from"./ui/UI.js";import{DesignStore}from"./customization/DesignStore.js";import{Designer}from"./customization/Designer.js";
const ui=new UI,store=new DesignStore,game=new Game(document.getElementById("gameCanvas"),ui,store),designer=new Designer(ui,store,()=>{game.starfield.sync()});
const qp=new URLSearchParams(location.search),requested=qp.get("lang"),storedLang=localStorage.getItem("helveticshotLanguage"),lang=requested==="en"||requested==="de"?requested:(storedLang||"de");
const T={de:{start:"SPIEL STARTEN",demo:"TRAILER DEMO",manual:"SPIELANLEITUNG",designer:"DESIGNER",back:"ZURÜCK",startLabel:"START-LEVEL",sound:"SOUND",language:"SPRACHE",background:"HINTERGRUND",resetStats:"STATISTIK RESET",manualTitle:"SPIELANLEITUNG",manualHtml:`<h3>Ziel</h3><p>Zerstöre die Gegner, sammle Punkte und überstehe möglichst viele Level. Jeder 5. Level ist ein Boss-Level.</p><h3>Start-Level freischalten</h3><p>Level 1 ist immer verfügbar. Level 5, 10, 15, 20 und 25 werden als Start-Level freigeschaltet, wenn das jeweilige Level <b>10-mal erfolgreich abgeschlossen</b> wurde. Nur tatsächlich gespielte und abgeschlossene Level zählen.</p><h3>Hintergründe</h3><p>SWISS ist der Standard. SPACE und CUSTOM sind auswählbar. Eigene Hintergrundwerte beeinflussen die Spielregeln nicht.</p><h3>Designer</h3><p>Schiff, drei Gegner-Units und Boss können gestaltet werden. Hitboxen, Geschwindigkeit, HP und Feuerwerte bleiben fest.</p><h3>Trailer Demo</h3><p>Der Demo-Modus zeigt reproduzierbare echte Spielszenen und verändert weder Highscore, Statistik noch Start-Level-Freischaltungen.</p><h3>Cloudflare Sprache</h3><p>Wird das Spiel mit <b>?lang=en</b> geöffnet, startet es automatisch auf Englisch. <b>?lang=de</b> startet Deutsch.</p>`},en:{start:"START GAME",demo:"TRAILER DEMO",manual:"GAME MANUAL",designer:"DESIGNER",back:"BACK",startLabel:"START LEVEL",sound:"SOUND",language:"LANGUAGE",background:"BACKGROUND",resetStats:"RESET STATS",manualTitle:"GAME MANUAL",manualHtml:`<h3>Goal</h3><p>Destroy the enemies, score points and survive as many levels as possible. Every 5th level is a boss level.</p><h3>Unlock start levels</h3><p>Level 1 is always available. Levels 5, 10, 15, 20 and 25 become selectable start levels after the respective level has been <b>successfully completed 10 times</b>. Only levels actually played and completed count.</p><h3>Backgrounds</h3><p>SWISS is the default. SPACE and CUSTOM remain selectable. Background visuals never change gameplay rules.</p><h3>Designer</h3><p>The ship, three enemy units and the boss can be customized. Hitboxes, speed, HP and fire parameters remain fixed.</p><h3>Trailer Demo</h3><p>Demo mode creates reproducible real gameplay scenes and never changes high score, statistics or start-level unlocks.</p><h3>Cloudflare language</h3><p>Opening the game with <b>?lang=en</b> starts it in English. <b>?lang=de</b> starts German.</p>`}};
function applyLanguage(l){localStorage.setItem("helveticshotLanguage",l);game.language=l;document.documentElement.lang=l;ui.languageSelect.value=l;ui.startButton.textContent=T[l].start;ui.demoButton.textContent=T[l].demo;ui.manualButton.textContent=T[l].manual;ui.designerButton.textContent=T[l].designer;ui.manualBackButton.textContent=T[l].back;ui.designerBackButton.textContent=T[l].back;ui.settingsStartLabel.textContent=T[l].startLabel;ui.settingsSoundLabel.textContent=T[l].sound;ui.settingsLanguageLabel.textContent=T[l].language;ui.settingsBackgroundLabel.textContent=T[l].background;ui.resetStatsButton.textContent=T[l].resetStats;ui.manualTitle.textContent=T[l].manualTitle;ui.manualText.innerHTML=T[l].manualHtml;ui.setStats(game.stats,l);refreshProgress()}
function refreshProgress(){const saved=Number(localStorage.getItem("helveticshotStartLevel")||1);ui.setStartLevels(game.levelProgress,saved,game.language||"de")}
game.onProgressChanged=refreshProgress;
ui.languageSelect.addEventListener("change",()=>applyLanguage(ui.languageSelect.value));
ui.backgroundSelect.value=store.design.background.theme||"swiss";
ui.backgroundSelect.addEventListener("change",()=>{store.design.background.theme=ui.backgroundSelect.value;store.save();designer.renderBackgroundControls();game.starfield.sync()});
const settings=()=>({level:Number(ui.startLevel.value||1),sound:ui.soundToggle.checked});
ui.startButton.addEventListener("click",()=>{const s=settings();localStorage.setItem("helveticshotStartLevel",s.level);localStorage.setItem("helveticshotSound",s.sound?"1":"0");game.setTestMode(ui.testMode.value,ui.testIntensity.value);game.start(s.level,s.sound)});
ui.demoButton.addEventListener("click",()=>game.startDemo(ui.soundToggle.checked));
ui.manualButton.addEventListener("click",()=>ui.showManual());ui.manualBackButton.addEventListener("click",()=>ui.showMenu());ui.designerButton.addEventListener("click",()=>ui.showDesigner());ui.designerBackButton.addEventListener("click",()=>ui.showMenu());ui.restartButton.addEventListener("click",()=>game.restart());ui.gameOverMenuButton.addEventListener("click",()=>game.toMenu());ui.pauseButton.addEventListener("click",()=>game.togglePause());ui.resumeButton.addEventListener("click",()=>game.togglePause());ui.pauseMenuButton.addEventListener("click",()=>game.toMenu());
addEventListener("keydown",e=>{if((e.code==="KeyP"||e.code==="Escape")&&(game.state==="playing"||game.state==="paused")){e.preventDefault();game.togglePause()}});
const ss=localStorage.getItem("helveticshotSound");if(ss!==null)ui.soundToggle.checked=ss==="1";
const refreshLocalHi=()=>{if(ui.menuHighScore)ui.menuHighScore.textContent=String(game.highScore||0).padStart(6,"0")};refreshLocalHi();
ui.resetHighScoreButton?.addEventListener("click",()=>{if(confirm(game.language==="en"?"Reset local high score on this device/browser?":"Lokalen Highscore auf diesem Gerät/Browser wirklich zurücksetzen?")){game.highScore=0;localStorage.removeItem("helveticshotHighScore");localStorage.removeItem("retroInvadersHighScore");refreshLocalHi();game.syncHud()}});
ui.resetStatsButton?.addEventListener("click",()=>{if(confirm(game.language==="en"?"Reset local game statistics?":"Lokale Spielstatistik wirklich zurücksetzen?")){game.stats={games:0,totalLevel:0,bestLevel:0,deaths:{},lastScore:0,totalSeconds:0};game.saveStats();ui.setStats(game.stats,game.language)}});
addEventListener("storage",refreshLocalHi);applyLanguage(lang);refreshProgress();
