export class UI{
 constructor(){const g=id=>document.getElementById(id);["gameShell","startScreen","manualScreen","designerScreen","levelScreen","gameOverScreen","pauseScreen","score","hudHighScore","level","lives","finalScore","highScore","levelTitle","levelSubtitle","startLevel","startLevelProgress","soundToggle","languageSelect","backgroundSelect","startButton","demoButton","manualButton","manualBackButton","designerButton","designerBackButton","restartButton","gameOverMenuButton","pauseButton","resumeButton","pauseMenuButton","leftButton","rightButton","fireButton","powerStatus","gamepadStatus","demoBadge","shipGrid","shipPalette","invaderGrid","invaderPalette","invaderType","bossGrid","bossPalette","shipMirrorButton","shipResetButton","invaderMirrorButton","invaderResetButton","bossMirrorButton","bossResetButton","bgTheme","bgColor","starColor","starDensity","starSpeed","scanlines","planetMode","backgroundPreview","saveDesignButton","exportDesignButton","importDesignInput","designerStatus","menuHighScore","resetHighScoreButton","statsLine","resetStatsButton","manualTitle","manualText","settingsStartLabel","settingsSoundLabel","settingsLanguageLabel","settingsBackgroundLabel"].forEach(id=>this[id]=g(id))}
 hideScreens(){[this.startScreen,this.manualScreen,this.designerScreen,this.levelScreen,this.gameOverScreen,this.pauseScreen].forEach(s=>s.classList.remove("active"))}
 showMenu(){this.hideScreens();this.startScreen.classList.add("active");this.gameShell.classList.remove("playing")}
 showManual(){this.hideScreens();this.manualScreen.classList.add("active")}
 showDesigner(){this.hideScreens();this.designerScreen.classList.add("active")}
 showPlaying(){this.hideScreens();this.gameShell.classList.add("playing")}
 showPause(){this.hideScreens();this.pauseScreen.classList.add("active");this.gameShell.classList.add("playing")}
 showLevel(l){this.levelTitle.textContent=`LEVEL ${l}`;this.levelSubtitle.textContent=l%5===0?"BOSS BATTLE":"INCOMING WAVE";this.levelScreen.classList.add("active")}
 hideLevel(){this.levelScreen.classList.remove("active")}
 showGameOver(s,h){this.hideScreens();this.finalScore.textContent=s;this.highScore.textContent=h;this.gameOverScreen.classList.add("active");this.gameShell.classList.remove("playing")}
 setHud(s,l,life,h){this.score.textContent=String(s).padStart(6,"0");this.hudHighScore.textContent=String(h).padStart(6,"0");if(this.menuHighScore)this.menuHighScore.textContent=String(h).padStart(6,"0");this.level.textContent=String(l).padStart(2,"0");this.lives.textContent=life}
 setGamepadConnected(v){this.gamepadStatus.textContent=v?"GAMEPAD: OK":"GAMEPAD: --"}
 setPowerStatus(p){const a=[];if(p.rapidTimer>0)a.push(`R ${p.rapidTimer.toFixed(0)}s`);if(p.shieldTimer>0)a.push(`S ${p.shieldTimer.toFixed(0)}s`);if(p.spreadTimer>0)a.push(`3 ${p.spreadTimer.toFixed(0)}s`);this.powerStatus.textContent=a.length?`POWER: ${a.join(" / ")}`:"POWER: --"}
 setStats(s,lang="de"){if(!this.statsLine)return;const avg=s.games?(s.totalLevel/s.games).toFixed(1):"0.0";let death="--",n=-1;for(const[k,v]of Object.entries(s.deaths||{}))if(v>n){n=v;death=k}this.statsLine.textContent=lang==="en"?`GAMES ${s.games} · AVG LEVEL ${avg} · BEST ${s.bestLevel||0} · DEATH ${death}`:`SPIELE ${s.games} · Ø LEVEL ${avg} · BEST ${s.bestLevel||0} · TOD ${death}`}
 setStartLevels(progress,current=1,lang="de"){const ms=[1,5,10,15,20,25];this.startLevel.innerHTML="";for(const l of ms){const count=progress[String(l)]||0,unlocked=l===1||count>=10;if(unlocked){const o=document.createElement("option");o.value=String(l);o.textContent=String(l);this.startLevel.appendChild(o)}}if([...this.startLevel.options].some(o=>o.value===String(current)))this.startLevel.value=String(current);else this.startLevel.value="1";const parts=ms.slice(1).map(l=>{const c=Math.min(10,progress[String(l)]||0);return c>=10?`L${l} ✓`:`L${l} ${c}/10`});this.startLevelProgress.textContent=(lang==="en"?"UNLOCK: ":"FREISCHALTUNG: ")+parts.join(" · ")}
 setDemo(v){if(this.demoBadge)this.demoBadge.style.display=v?"block":"none"}
}
