import{COLORS}from"./Defaults.js";
export class Designer{
 constructor(ui,store,onChanged){this.ui=ui;this.store=store;this.onChanged=onChanged;this.shipColor=COLORS[0];this.invaderColor=COLORS[2];this.bossColor=COLORS[2];this.invaderType=0;this.bind();this.renderAll()}
 bind(){document.querySelectorAll(".tabButton").forEach(b=>b.addEventListener("click",()=>this.switchTab(b.dataset.tab)));
 this.ui.invaderType.addEventListener("change",()=>{this.invaderType=Number(this.ui.invaderType.value);this.renderInvader()});
 this.ui.shipMirrorButton.addEventListener("click",()=>{this.store.design.ship=this.store.design.ship.map(r=>[...r].reverse());this.renderShip()});
 this.ui.invaderMirrorButton.addEventListener("click",()=>{this.store.design.invaders[this.invaderType]=this.store.design.invaders[this.invaderType].map(r=>[...r].reverse());this.renderInvader()});
 this.ui.bossMirrorButton.addEventListener("click",()=>{this.store.design.boss=this.store.design.boss.map(r=>[...r].reverse());this.renderBoss()});
 this.ui.shipResetButton.addEventListener("click",()=>{this.store.resetShip();this.renderShip()});
 this.ui.invaderResetButton.addEventListener("click",()=>{this.store.resetInvader(this.invaderType);this.renderInvader()});
 this.ui.bossResetButton.addEventListener("click",()=>{this.store.resetBoss();this.renderBoss()});
 [this.ui.bgTheme,this.ui.bgColor,this.ui.starColor,this.ui.starDensity,this.ui.starSpeed,this.ui.scanlines,this.ui.planetMode].forEach(el=>el.addEventListener("input",()=>this.readBackgroundControls()));
 this.ui.saveDesignButton.addEventListener("click",()=>{this.readBackgroundControls(false);this.store.save();this.onChanged();this.status("Design gespeichert / saved.")});
 this.ui.exportDesignButton.addEventListener("click",()=>this.exportDesign());
 this.ui.importDesignInput.addEventListener("change",e=>this.importDesign(e))}
 switchTab(name){document.querySelectorAll(".tabButton").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));["ship","invader","boss","background"].forEach(n=>document.getElementById(n+"Tab").classList.toggle("active",n===name));if(name==="background")this.drawBackgroundPreview()}
 makePalette(el,current,setter){el.innerHTML="";COLORS.forEach(c=>{const b=document.createElement("button");b.className="colorSwatch"+(c===current?" active":"");b.style.background=c==="transparent"?"repeating-conic-gradient(#333 0 25%,#777 0 50%) 0/10px 10px":c;b.title=c;b.addEventListener("click",()=>{setter(c);this.makePalette(el,c,setter)});el.appendChild(b)})}
 renderGrid(el,data,onPaint,cellClass="pixelCell"){el.innerHTML="";data.forEach((row,y)=>row.forEach((c,x)=>{const b=document.createElement("button");b.className=cellClass;b.style.background=c||"transparent";b.addEventListener("pointerdown",e=>{e.preventDefault();onPaint(x,y)});el.appendChild(b)}))}
 renderShip(){this.makePalette(this.ui.shipPalette,this.shipColor,c=>this.shipColor=c);this.renderGrid(this.ui.shipGrid,this.store.design.ship,(x,y)=>{this.store.design.ship[y][x]=this.shipColor==="transparent"?null:this.shipColor;this.renderShip()})}
 renderInvader(){this.makePalette(this.ui.invaderPalette,this.invaderColor,c=>this.invaderColor=c);this.renderGrid(this.ui.invaderGrid,this.store.design.invaders[this.invaderType],(x,y)=>{this.store.design.invaders[this.invaderType][y][x]=this.invaderColor==="transparent"?null:this.invaderColor;this.renderInvader()})}
 renderBoss(){this.makePalette(this.ui.bossPalette,this.bossColor,c=>this.bossColor=c);this.renderGrid(this.ui.bossGrid,this.store.design.boss,(x,y)=>{this.store.design.boss[y][x]=this.bossColor==="transparent"?null:this.bossColor;this.renderBoss()},"bossPixelCell")}
 renderBackgroundControls(){const b=this.store.design.background;this.ui.bgTheme.value=b.theme||"swiss";this.ui.bgColor.value=b.bgColor;this.ui.starColor.value=b.starColor;this.ui.starDensity.value=b.starDensity;this.ui.starSpeed.value=b.starSpeed;this.ui.scanlines.value=b.scanlines;this.ui.planetMode.value=b.planetMode;this.drawBackgroundPreview()}
 readBackgroundControls(redraw=true){Object.assign(this.store.design.background,{theme:this.ui.bgTheme.value,bgColor:this.ui.bgColor.value,starColor:this.ui.starColor.value,starDensity:Number(this.ui.starDensity.value),starSpeed:Number(this.ui.starSpeed.value),scanlines:Number(this.ui.scanlines.value),planetMode:this.ui.planetMode.value});if(redraw)this.drawBackgroundPreview()}
 drawBackgroundPreview(){const c=this.ui.backgroundPreview,ctx=c.getContext("2d"),b=this.store.design.background;ctx.clearRect(0,0,c.width,c.height);if(b.theme==="swiss"){const img=new Image;img.onload=()=>{ctx.drawImage(img,0,0,c.width,c.height);ctx.fillStyle="rgba(0,0,12,.25)";ctx.fillRect(0,0,c.width,c.height)};img.src="./assets/backgrounds/swiss_default.png";return}ctx.fillStyle=b.theme==="space"?"#020615":b.bgColor;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle=b.starColor;for(let i=0;i<Math.floor(b.starDensity*.5);i++){const x=(i*73)%c.width,y=(i*47)%c.height;ctx.fillRect(x,y,i%9===0?2:1,i%9===0?2:1)}if(b.theme==="custom"&&b.planetMode==="moon"){ctx.fillStyle="#8a8a9a";ctx.beginPath();ctx.arc(300,48,32,0,Math.PI*2);ctx.fill()}if(b.theme==="custom"&&b.planetMode==="saturn"){ctx.strokeStyle="#d8b66a";ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(290,55,50,14,-.2,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#b58b4f";ctx.beginPath();ctx.arc(290,55,24,0,Math.PI*2);ctx.fill()}}
 exportDesign(){this.store.save();const blob=new Blob([this.store.exportJson()],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="HELVETICSHOT_84_Design_v0.5.4.1.json";a.click();URL.revokeObjectURL(a.href);this.status("Design exportiert / exported.")}
 async importDesign(e){const f=e.target.files?.[0];if(!f)return;try{if(f.size>65536)throw new Error("Datei zu gross (max. 64 KB) / file too large");if(!/\.json$/i.test(f.name))throw new Error("Nur JSON-Dateien / JSON files only");this.store.importJson(await f.text());this.renderAll();this.onChanged();this.status("Design importiert / imported.")}catch(err){this.status("Importfehler / import error: "+err.message)}finally{e.target.value=""}}
 renderAll(){this.renderShip();this.renderInvader();this.renderBoss();this.renderBackgroundControls()}
 status(t){this.ui.designerStatus.textContent=t;setTimeout(()=>{if(this.ui.designerStatus.textContent===t)this.ui.designerStatus.textContent=""},3000)}
}
